apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-monitor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-monitor-agent
  template:
    metadata:
      labels:
        app: cart-monitor-agent
    spec:
      containers:
      - name: cart-monitor-agent
        image: us-west1-docker.pkg.dev/<PROJECT_ID>/gke-hackathon/cart-monitor-agent:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        resources:
          requests:
            memory: 512Mi
            cpu: 1
          limits:
            memory: 1Gi
            cpu: 2
        ports:
        - containerPort: 10102
        env:
          - name: PORT
            value: '10102'
          - name: AGENT_MODULE
            value: 'cart_monitor_agent'
          - name: GOOGLE_CLOUD_PROJECT
            value: <PROJECT_ID>
          - name: GOOGLE_CLOUD_LOCATION
            value: 'us-west1'
          - name: GOOGLE_GENAI_USE_VERTEXAI
            value: 'False'
          - name: GOOGLE_API_KEY
            value: <GOOGLE_API_KEY>
          - name: MCP_SERVER_HOST
            value: 'ob-mcp-server'
          - name: MCP_SERVER_PORT
            value: '8080'
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: cart-monitor-agent
spec:
  type: ClusterIP
  ports:
    - port: 10102
      targetPort: 10102
  selector:
    app: cart-monitor-agent
